analyzer:
  errors:
    use_build_context_synchronously: ignore
    only_throw_errors: ignore
    deprecated_member_use: ignore
    inference_failure_on_instance_creation: ignore
    use_if_null_to_convert_nulls_to_bools: ignore
    omit_local_variable_types: ignore
include: package:very_good_analysis/analysis_options.yaml

# Pragmatic relax to avoid noise for this mock project
linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    always_use_package_imports: false
    directives_ordering: false
    cascade_invocations: false
    require_trailing_commas: false
    prefer_int_literals: false
    sort_pub_dependencies: false
